In [1]:
import pandas as pd

In [11]:
mydict = {'col1':[1,2,3,4,5],
          'col2': [6,7,8,9,10],
          'col3': ['one','two','three','four','five']}
mydict

{'col1': [1, 2, 3, 4, 5],
 'col2': [6, 7, 8, 9, 10],
 'col3': ['one', 'two', 'three', 'four', 'five']}

In [12]:
df = pd.DataFrame(mydict)
df

   col1  col2   col3
0     1     6    one
1     2     7    two
2     3     8  three
3     4     9   four
4     5    10   five

In [13]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [14]:
df.col2

0     6
1     7
2     8
3     9
4    10
Name: col2, dtype: int64

In [15]:
df1 = df[['col1', 'col2']]
df1

   col1  col2
0     1     6
1     2     7
2     3     8
3     4     9
4     5    10

In [16]:
# Display all rows where:
# col1 > 1
# and col2 != 7

df[(df.col1 > 1) & (df.col2 != 7)]

   col1  col2   col3
2     3     8  three
3     4     9   four
4     5    10   five

In [18]:
# dipaly col3 is not equal to three
df[(df.col3 != 'three')]

   col1  col2  col3
0     1     6   one
1     2     7   two
3     4     9  four
4     5    10  five

In [19]:
df.iloc[0:3]

   col1  col2   col3
0     1     6    one
1     2     7    two
2     3     8  three

In [24]:
df.iloc[0:3][['col1','col2']]

   col1  col2
0     1     6
1     2     7
2     3     8

In [25]:
# find the col1 values greater than 2
df.loc[df['col1']> 2]

   col1  col2   col3
2     3     8  three
3     4     9   four
4     5    10   five

In [28]:
df.loc[0:3].query('col1> 2')

   col1  col2   col3
2     3     8  three
3     4     9   four

In [29]:
df.query('2*col1 >= col2')

   col1  col2  col3
4     5    10  five

In [ ]:
# if we use single quote in brackets then use outer bracket double quote ["['']"]
df.query("col3 in['three','four']")

   col1  col2   col3
2     3     8  three
3     4     9   four

In [34]:
df.query("col3 not in['three','four']")

   col1  col2  col3
0     1     6   one
1     2     7   two
4     5    10  five

In [35]:
df.query("col2 != [5,7]")

   col1  col2   col3
0     1     6    one
2     3     8  three
3     4     9   four
4     5    10   five