In [2]:
import pandas as pd

In [6]:
tpl = ((1001, 'vrushabh'),(1002, 'aniket'), (1003, 'ajay'), (1004, 'om'), (1005, 'tushar'))
tpl

((1001, 'vrushabh'),
 (1002, 'aniket'),
 (1003, 'ajay'),
 (1004, 'om'),
 (1005, 'tushar'))

In [7]:
df = pd.DataFrame(tpl, columns=['col1', 'col2'])
df

   col1      col2
0  1001  vrushabh
1  1002    aniket
2  1003      ajay
3  1004        om
4  1005    tushar

In [8]:
# rename the column name
df.rename(columns={'col1': 'empid', 'col2': 'name'}, inplace=True)
df

   empid      name
0   1001  vrushabh
1   1002    aniket
2   1003      ajay
3   1004        om
4   1005    tushar

In [9]:
# add third col3 or new col
df['dept'] = ['IT', 'finance', 'engineering', 'medical', 'art']
df

   empid      name         dept
0   1001  vrushabh           IT
1   1002    aniket      finance
2   1003      ajay  engineering
3   1004        om      medical
4   1005    tushar          art

In [14]:
#  how to insert new col in betw existing col
df.insert(loc=1, column = 'salary2', value = [35000, 22000, 50000, 54001,4000])

In [15]:
df

   empid  salary2  salary1      name         dept
0   1001    35000    35000  vrushabh           IT
1   1002    22000    22000    aniket      finance
2   1003    50000    50000      ajay  engineering
3   1004    54001    54001        om      medical
4   1005     4000     4000    tushar          art

In [ ]:
#  insert phone number col in betw name and dept col
df.insert(loc=4, column = 'phone no', value=[1010101010, 84848484,487484884,48609876,57754884])
df

   empid  salary2  salary1      name    phone no         dept
0   1001    35000    35000  vrushabh  1010101010           IT
1   1002    22000    22000    aniket    84848484      finance
2   1003    50000    50000      ajay   487484884  engineering
3   1004    54001    54001        om    48609876      medical
4   1005     4000     4000    tushar    57754884          art

In [17]:
df.drop("salary2", axis=1, inplace=True)

In [18]:
df

   empid  salary1      name    phone no         dept
0   1001    35000  vrushabh  1010101010           IT
1   1002    22000    aniket    84848484      finance
2   1003    50000      ajay   487484884  engineering
3   1004    54001        om    48609876      medical
4   1005     4000    tushar    57754884          art

In [ ]:
# creating a new column from existing colum
df['tax'] = df['salary1'] * 10/100
df

   empid  salary1      name    phone no         dept     tax
0   1001    35000  vrushabh  1010101010           IT  3500.0
1   1002    22000    aniket    84848484      finance  2200.0
2   1003    50000      ajay   487484884  engineering  5000.0
3   1004    54001        om    48609876      medical  5400.1
4   1005     4000    tushar    57754884          art   400.0

In [22]:
#  create a new col from exiting col using lambda
df1 = df.assign(pf = lambda x: x.salary1 * 10/10)
df1

   empid  salary1      name    phone no         dept     tax       pf
0   1001    35000  vrushabh  1010101010           IT  3500.0  35000.0
1   1002    22000    aniket    84848484      finance  2200.0  22000.0
2   1003    50000      ajay   487484884  engineering  5000.0  50000.0
3   1004    54001        om    48609876      medical  5400.1  54001.0
4   1005     4000    tushar    57754884          art   400.0   4000.0

In [24]:
# cal net salary net sal = salary - tax - pf
df2 = df1.assign(netsal = lambda x: x.salary1-x.tax-x.pf)
df2

   empid  salary1      name    phone no         dept     tax       pf  netsal
0   1001    35000  vrushabh  1010101010           IT  3500.0  35000.0 -3500.0
1   1002    22000    aniket    84848484      finance  2200.0  22000.0 -2200.0
2   1003    50000      ajay   487484884  engineering  5000.0  50000.0 -5000.0
3   1004    54001        om    48609876      medical  5400.1  54001.0 -5400.1
4   1005     4000    tushar    57754884          art   400.0   4000.0  -400.0

In [25]:
#  cal deduction = tax + pf
df3 = df1.assign(deduction = lambda x: x.tax+x.pf)
df3

,empid,salary1,name,phone no,dept,tax,pf,deduction
0,1001,35000,vrushabh,1010101010,IT,3500.0,35000.0,38500.0
1,1002,22000,aniket,84848484,finance,2200.0,22000.0,24200.0
2,1003,50000,ajay,487484884,engineering,5000.0,50000.0,55000.0
3,1004,54001,om,48609876,medical,5400.1,54001.0,59401.1
4,1005,4000,tushar,57754884,art,400.0,4000.0,4400.0