In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(
    r'C:\Users\91942\Downloads\datasets1\datasets1\textdata.txt',
    sep=r'\s+',
    names=['A', 'B', 'C', 'Person']
)
df

   A  B      C   Person
0  1  1   2.92    Vijay
1  1  2  70.75    Kumar
2  1  3  60.90    Vinay
3  2  1  71.34     Anil
4  2  2   5.23    Ashok
5  2  3  38.56   Neeraj
6  3  1  61.24     Sita
7  3  2  38.68    Laxmi
8  3  3   4.49  Chandra

In [5]:
df = pd.read_csv(r'C:\Users\91942\Downloads\datasets1\datasets1\empdata1.csv',)
df

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003             NaN  18000.33  03-03-02
3   1004    Hema Chandra       NaN       NaN
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [6]:
df.loc[:,'ename']

0        Ganesh Rao
1        Anil Kumar
2               NaN
3      Hema Chandra
4    Laxmi Prasanna
5         Anant Nag
Name: ename, dtype: object

In [7]:
df.loc[:, 'doj']

0    10-10-00
1    03-03-02
2    03-03-02
3         NaN
4    10-08-00
5    09-09-99
Name: doj, dtype: object

In [8]:
df.iloc[:, 3]

0    10-10-00
1    03-03-02
2    03-03-02
3         NaN
4    10-08-00
5    09-09-99
Name: doj, dtype: object

In [ ]:
df.iloc[:,[3]] # 👉 "Give me all rows (:) from column index 3 (doj)"

        doj
0  10-10-00
1  03-03-02
2  03-03-02
3       NaN
4  10-08-00
5  09-09-99

In [11]:
# to see more than one column
df.loc[:, ['ename', 'sal', 'doj']]

            ename       sal       doj
0      Ganesh Rao  10000.00  10-10-00
1      Anil Kumar  23000.50  03-03-02
2             NaN  18000.33  03-03-02
3    Hema Chandra       NaN       NaN
4  Laxmi Prasanna  12000.75  10-08-00
5       Anant Nag   9999.99  09-09-99

In [13]:
# "Display all rows and only the first two columns of the DataFrame."
df.iloc[:,[0,1]]

   empid           ename
0   1001      Ganesh Rao
1   1002      Anil Kumar
2   1003             NaN
3   1004    Hema Chandra
4   1005  Laxmi Prasanna
5   1006       Anant Nag

In [15]:
# to see range rows
df.loc[2:3, ['ename', 'sal']]

          ename       sal
2           NaN  18000.33
3  Hema Chandra       NaN

In [ ]:
df.iloc[2:3, [2,3]] # iloc only accept the int not a string

        sal       doj
2  18000.33  03-03-02

In [18]:
df.iloc[0:3, [1,2]]

        ename       sal
0  Ganesh Rao  10000.00
1  Anil Kumar  23000.50
2         NaN  18000.33

In [ ]:
# to display last row
df.iloc[-1]

empid         1006
ename    Anant Nag
sal        9999.99
doj       09-09-99
Name: 5, dtype: object

In [20]:
# to retrive last column
df.loc[:,'doj']

0    10-10-00
1    03-03-02
2    03-03-02
3         NaN
4    10-08-00
5    09-09-99
Name: doj, dtype: object

In [ ]:
df.iloc[:, -1]  # "Give me all rows from the last column."

0    10-10-00
1    03-03-02
2    03-03-02
3         NaN
4    10-08-00
5    09-09-99
Name: doj, dtype: object

In [24]:
# to find the dataset size
df.shape

(6, 4)

In [25]:
# to display the first 5 rows of a DataFrame.
df.head()

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003             NaN  18000.33  03-03-02
3   1004    Hema Chandra       NaN       NaN
4   1005  Laxmi Prasanna  12000.75  10-08-00

In [ ]:
df.tail()  # for last 5 rows

   empid           ename       sal       doj
1   1002      Anil Kumar  23000.50  03-03-02
2   1003             NaN  18000.33  03-03-02
3   1004    Hema Chandra       NaN       NaN
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [27]:
# display all the columns
df.columns

Index(['empid', 'ename', 'sal', 'doj'], dtype='object')

In [28]:
# "Display rows from index 2 up to (but not including) index 5."
df[2:5]

   empid           ename       sal       doj
2   1003             NaN  18000.33  03-03-02
3   1004    Hema Chandra       NaN       NaN
4   1005  Laxmi Prasanna  12000.75  10-08-00

In [ ]:
# alternate rows  diff 3
df[::3]

   empid         ename      sal       doj
0   1001    Ganesh Rao  10000.0  10-10-00
3   1004  Hema Chandra      NaN       NaN

In [32]:
# display rows reverse number
df[:: -1]

   empid           ename       sal       doj
5   1006       Anant Nag   9999.99  09-09-99
4   1005  Laxmi Prasanna  12000.75  10-08-00
3   1004    Hema Chandra       NaN       NaN
2   1003             NaN  18000.33  03-03-02
1   1002      Anil Kumar  23000.50  03-03-02
0   1001      Ganesh Rao  10000.00  10-10-00

In [38]:
# alternate rows with col
df[::2][['ename', 'doj','sal']]

            ename       doj       sal
0      Ganesh Rao  10-10-00  10000.00
2             NaN  03-03-02  18000.33
4  Laxmi Prasanna  10-08-00  12000.75

In [ ]:
df # all data are printed

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003             NaN  18000.33  03-03-02
3   1004    Hema Chandra       NaN       NaN
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [40]:
# to know the max sal
df.sal.max()

np.float64(23000.5)

In [41]:
# to know the min sal
df.sal.min()

np.float64(9999.99)

In [42]:
# to display max sal diff way
df['sal'].max()

np.float64(23000.5)

In [ ]:
df.sal.mean()  # mean of sal

np.float64(14600.314000000002)

In [ ]:
df['sal'].mean() # mean of sal

np.float64(14600.314000000002)

In [46]:
# avg salary
print("the avg sal is = ", df.sal.mean())

the avg sal is =  14600.314000000002

In [47]:
#  to print stastical info
df.describe()

             empid           sal
count     6.000000      5.000000
mean   1003.500000  14600.314000
std       1.870829   5727.277635
min    1001.000000   9999.990000
25%    1002.250000  10000.000000
50%    1003.500000  12000.750000
75%    1004.750000  18000.330000
max    1006.000000  23000.500000

In [ ]:
# sal is greater than 5000  # 2 df for nothingh but the masking
df[df['sal'] > 5000]

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003             NaN  18000.33  03-03-02
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [ ]:
# in between 10000 and 20000
df[(df['sal']>10000) & (df['sal']<20000)]

   empid           ename       sal       doj
2   1003             NaN  18000.33  03-03-02
4   1005  Laxmi Prasanna  12000.75  10-08-00

In [54]:
df[(df['sal']>10000) & (df.sal<20000)]

   empid           ename       sal       doj
2   1003             NaN  18000.33  03-03-02
4   1005  Laxmi Prasanna  12000.75  10-08-00

In [ ]:
# "Make the empid column the index of the DataFrame and update the original DataFrame.
df.set_index('empid', inplace=True)

In [56]:
df

                ename       sal       doj
empid
1001       Ganesh Rao  10000.00  10-10-00
1002       Anil Kumar  23000.50  03-03-02
1003              NaN  18000.33  03-03-02
1004     Hema Chandra       NaN       NaN
1005   Laxmi Prasanna  12000.75  10-08-00
1006        Anant Nag   9999.99  09-09-99

In [59]:
# for reset the values empid
df.reset_index('empid', inplace=True)

In [60]:
df.loc[1]

empid          1002
ename    Anil Kumar
sal         23000.5
doj        03-03-02
Name: 1, dtype: object

In [61]:
# sorting desc order
df.sort_values('ename', ascending=False)

   empid           ename       sal       doj
4   1005  Laxmi Prasanna  12000.75  10-08-00
3   1004    Hema Chandra       NaN       NaN
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
5   1006       Anant Nag   9999.99  09-09-99
2   1003             NaN  18000.33  03-03-02

In [63]:
# for sorting indexing
df.sort_values('empid', ascending=False)

   empid           ename       sal       doj
5   1006       Anant Nag   9999.99  09-09-99
4   1005  Laxmi Prasanna  12000.75  10-08-00
3   1004    Hema Chandra       NaN       NaN
2   1003             NaN  18000.33  03-03-02
1   1002      Anil Kumar  23000.50  03-03-02
0   1001      Ganesh Rao  10000.00  10-10-00

In [64]:
df.sort_values(by = ['doj', 'sal'], ascending=[False, True])

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99
2   1003             NaN  18000.33  03-03-02
1   1002      Anil Kumar  23000.50  03-03-02
3   1004    Hema Chandra       NaN       NaN