In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r'C:\Users\91942\Downloads\datasets1\datasets1\empdata1.csv')
df

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003             NaN  18000.33  03-03-02
3   1004    Hema Chandra       NaN       NaN
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [5]:
df.fillna(0, inplace=True)
df

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003               0  18000.33  03-03-02
3   1004    Hema Chandra      0.00         0
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [9]:
avg = df['sal'].mean
avg

<bound method Series.mean of 0    10000.00
1    23000.50
2    18000.33
3        0.00
4    12000.75
5     9999.99
Name: sal, dtype: float64>

In [ ]:
df = df.fillna({'ename': 'no name', 'sal': avg, 'doj': '1/01/1997'}) # not give output bocz we
# ran a already fillnan inplace = true
df

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003               0  18000.33  03-03-02
3   1004    Hema Chandra      0.00         0
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99