In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\91942\Desktop\11.11\agree\SNOW\pandas\datasets1\datasets1\empdata.csv')
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [3]:
df.head()

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10

In [4]:
df.tail()

   empid           ename       sal         doj
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   empid   6 non-null      int64
 1   ename   6 non-null      object
 2   sal     6 non-null      float64
 3   doj     6 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

In [6]:
df.isnull()

   empid  ename    sal    doj
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False

In [7]:
df.fillna(0)

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [8]:
df.loc[0]

empid          1001
ename    Ganesh Rao
sal         10000.0
doj      2000-10-10
Name: 0, dtype: object

In [9]:
df.iloc[0]

empid          1001
ename    Ganesh Rao
sal         10000.0
doj      2000-10-10
Name: 0, dtype: object

In [10]:
df['doj']

0    2000-10-10
1    2002-03-03
2    2002-03-03
3    2002-03-03
4    2000-08-10
5    1999-09-09
Name: doj, dtype: object

In [11]:
df[['doj', 'empid']]

          doj  empid
0  2000-10-10   1001
1  2002-03-03   1002
2  2002-03-03   1003
3  2002-03-03   1004
4  2000-08-10   1005
5  1999-09-09   1006

In [12]:
df[df['empid'] > 10 ]

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [13]:
df[(df['empid'] > 1005) & (df['sal'] > 10000)]

Empty DataFrame
Columns: [empid, ename, sal, doj]
Index: []

In [14]:
df.sort_values('sal', ascending=False)

   empid           ename       sal         doj
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
0   1001      Ganesh Rao  10000.00  2000-10-10
5   1006       Anant Nag   9999.99  1999-09-09

In [15]:
df.sort_values('sal', ascending=False).head(5)

   empid           ename       sal         doj
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
0   1001      Ganesh Rao  10000.00  2000-10-10

In [16]:
df.query('empid > 1')

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [17]:
df['age'] = [10,20,30,40,50,60]

In [18]:
df.insert(1, 'custid',[1,2,3,4,5,6,])

In [19]:
df.rename(columns={'age': 'Age'})

   empid  custid           ename       sal         doj  Age
0   1001       1      Ganesh Rao  10000.00  2000-10-10   10
1   1002       2      Anil Kumar  23000.50  2002-03-03   20
2   1003       3    Gaurav Gupta  18000.33  2002-03-03   30
3   1004       4    Hema Chandra  16500.50  2002-03-03   40
4   1005       5  Laxmi Prasanna  12000.75  2000-08-10   50
5   1006       6       Anant Nag   9999.99  1999-09-09   60

In [20]:
df.drop('custid', axis = 1)

   empid           ename       sal         doj  age
0   1001      Ganesh Rao  10000.00  2000-10-10   10
1   1002      Anil Kumar  23000.50  2002-03-03   20
2   1003    Gaurav Gupta  18000.33  2002-03-03   30
3   1004    Hema Chandra  16500.50  2002-03-03   40
4   1005  Laxmi Prasanna  12000.75  2000-08-10   50
5   1006       Anant Nag   9999.99  1999-09-09   60

In [21]:
df.groupby('empid')

In [22]:
df.groupby('empid').size()

empid
1001    1
1002    1
1003    1
1004    1
1005    1
1006    1
dtype: int64

In [23]:
df.groupby('empid')['sal'].mean()

empid
1001    10000.00
1002    23000.50
1003    18000.33
1004    16500.50
1005    12000.75
1006     9999.99
Name: sal, dtype: float64

In [24]:
df.groupby('empid').agg({
    'sal':['min','max'],
    'doj':['min', 'max']
})

            sal                   doj
            min       max         min         max
empid
1001   10000.00  10000.00  2000-10-10  2000-10-10
1002   23000.50  23000.50  2002-03-03  2002-03-03
1003   18000.33  18000.33  2002-03-03  2002-03-03
1004   16500.50  16500.50  2002-03-03  2002-03-03
1005   12000.75  12000.75  2000-08-10  2000-08-10
1006    9999.99   9999.99  1999-09-09  1999-09-09

In [25]:
df['doj'].value_counts()

doj
2002-03-03    3
2000-10-10    1
2000-08-10    1
1999-09-09    1
Name: count, dtype: int64

In [26]:
df['empid'].unique()

array([1001, 1002, 1003, 1004, 1005, 1006])

In [27]:
df['empid'].nunique()

6

In [28]:
df

   empid  custid           ename       sal         doj  age
0   1001       1      Ganesh Rao  10000.00  2000-10-10   10
1   1002       2      Anil Kumar  23000.50  2002-03-03   20
2   1003       3    Gaurav Gupta  18000.33  2002-03-03   30
3   1004       4    Hema Chandra  16500.50  2002-03-03   40
4   1005       5  Laxmi Prasanna  12000.75  2000-08-10   50
5   1006       6       Anant Nag   9999.99  1999-09-09   60

In [32]:
df.where(df['age'] > 10, 'bad')

  empid custid           ename       sal         doj  age
0   bad    bad             bad       bad         bad  bad
1  1002      2      Anil Kumar   23000.5  2002-03-03   20
2  1003      3    Gaurav Gupta  18000.33  2002-03-03   30
3  1004      4    Hema Chandra   16500.5  2002-03-03   40
4  1005      5  Laxmi Prasanna  12000.75  2000-08-10   50
5  1006      6       Anant Nag   9999.99  1999-09-09   60

In [ ]:
df.groupby('age')['sal'].mean() # here we used () for the age coz we creating a grup by so its a method

age
10    10000.00
20    23000.50
30    18000.33
40    16500.50
50    12000.75
60     9999.99
Name: sal, dtype: float64