In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\91942\Desktop\11.11\agree\SNOW\pandas\datasets1\datasets1\shoppingmall.csv')

In [3]:
df.head(5)

   ID  Gender  Age  Income  Score
0   1    Male   19      15     39
1   2    Male   21      15     81
2   3  Female   20      16      6
3   4  Female   23      16     77
4   5  Female   31      17     40

In [4]:
# select * from cust limit 8
df.head(8)

   ID  Gender  Age  Income  Score
0   1    Male   19      15     39
1   2    Male   21      15     81
2   3  Female   20      16      6
3   4  Female   23      16     77
4   5  Female   31      17     40
5   6  Female   22      17     76
6   7  Female   35      18      6
7   8  Female   23      18     94

In [6]:
# select * from cust where income = 23 
df[df.Income == 23]

    ID  Gender  Age  Income  Score
18  19    Male   52      23     29
19  20  Female   35      23     98

In [11]:
# select * from cust where income = 23 and score=98
df[(df.Income == 23) & (df.Score == 98)]

    ID  Gender  Age  Income  Score
19  20  Female   35      23     98

In [ ]:
# only id and income
df[(df.Income == 23) & (df.Score == 98)][['ID', 'Income']]

    ID  Income
19  20      23

In [ ]:
# display min age, max age, avg age
df['Age'].min()

np.int64(18)

In [28]:
#  select * from cust where age = (select max(age) from cust
df[df['Age']==df['Age'].max()]

    ID Gender  Age  Income  Score
60  61   Male   70      46     56
70  71   Male   70      49     55

In [23]:
# method 2
df['Age'].agg(['min','max','mean'])

min     18.00
max     70.00
mean    38.85
Name: Age, dtype: float64

In [30]:
# to know unique income values
df['Income'].unique()

array([ 15,  16,  17,  18,  19,  20,  21,  23,  24,  25,  28,  29,  30,
        33,  34,  37,  38,  39,  40,  42,  43,  44,  46,  47,  48,  49,
        50,  54,  57,  58,  59,  60,  61,  62,  63,  64,  65,  67,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  81,  85,  86,
        87,  88,  93,  97,  98,  99, 101, 103, 113, 120, 126, 137])

In [33]:
# display only female records sorted on score in asc order
# SELECT * FROM cust WHERE Gender = ' Female' ORDER BY Score ASC
res = df[df.Gender == 'Female'].sort_values('Score')
print("the sorted all value is = ", res)

the sorted all value is =        ID  Gender  Age  Income  Score
22    23  Female   46      25      5
140  141  Female   57      75      5
6      7  Female   35      18      6
2      3  Female   20      16      6
136  137  Female   44      73      7
..   ...     ...  ...     ...    ...
163  164  Female   31      81     93
7      8  Female   23      18     94
167  168  Female   33      86     95
19    20  Female   35      23     98
11    12  Female   35      19     99

[112 rows x 5 columns]

In [34]:
# display only female records sorted on score in dsec order
# SELECT * FROM cust WHERE Gender = ' Female' ORDER BY Score DESC
df[df.Gender == 'Female'].sort_values('Score', ascending=False)

      ID  Gender  Age  Income  Score
11    12  Female   35      19     99
19    20  Female   35      23     98
167  168  Female   33      86     95
7      8  Female   23      18     94
163  164  Female   31      81     93
..   ...     ...  ...     ...    ...
136  137  Female   44      73      7
2      3  Female   20      16      6
6      7  Female   35      18      6
22    23  Female   46      25      5
140  141  Female   57      75      5

[112 rows x 5 columns]

In [ ]:
# diplay gender and age
# select * from cust group by gender, age 
df.groupby(['Gender', 'Age']).

In [41]:
# diplay gender and age
df[['Gender', 'Age']]

     Gender  Age
0      Male   19
1      Male   21
2    Female   20
3    Female   23
4    Female   31
..      ...  ...
195  Female   35
196  Female   45
197    Male   32
198    Male   32
199    Male   30

[200 rows x 2 columns]

In [48]:
# diplay gender and age
# select * from cust group by gender, age 
df.groupby(['Gender', 'Age']).size().to_frame('Count').reset_index().sort_values('Count', ascending=False)

    Gender  Age  Count
12  Female   31      7
13  Female   32      6
5   Female   23      6
16  Female   35      6
28  Female   49      6
..     ...  ...    ...
80    Male   64      1
82    Male   66      1
81    Male   65      1
84    Male   68      1
85    Male   69      1

[87 rows x 3 columns]

In [50]:
# dipaly the records with age 20, 30 or 40
#  select * from cust where age in (20, 30, 40)
res = df[df.Age.isin([20,30,40])]
print(res)

      ID  Gender  Age  Income  Score
2      3  Female   20      16      6
9     10  Female   30      19     72
17    18    Male   20      21     66
28    29  Female   40      29     31
37    38  Female   30      34     73
39    40  Female   20      37     75
77    78    Male   40      54     48
93    94  Female   40      60     40
99   100    Male   20      61     49
122  123  Female   40      69     58
127  128    Male   40      71     95
134  135    Male   20      73      5
157  158  Female   30      78     78
159  160  Female   30      78     73
170  171    Male   40      87     13
175  176  Female   30      88     86
185  186    Male   30      99     97
199  200    Male   30     137     83

In [51]:
# displayy the records with age not in 20, 30 or 40
# select * from cust where age not in (20, 30, 40)
df[~df.Age.isin([20,30,40])]

      ID  Gender  Age  Income  Score
0      1    Male   19      15     39
1      2    Male   21      15     81
3      4  Female   23      16     77
4      5  Female   31      17     40
5      6  Female   22      17     76
..   ...     ...  ...     ...    ...
194  195  Female   47     120     16
195  196  Female   35     120     79
196  197  Female   45     126     28
197  198    Male   32     126     74
198  199    Male   32     137     18

[182 rows x 5 columns]

In [54]:
# retrive top 10 rows after ordering on score in desc order
# select * from cust order by score desc limit 10
df.sort_values('Score', ascending=False).head(10)

      ID  Gender  Age  Income  Score
11    12  Female   35      19     99
19    20  Female   35      23     98
145  146    Male   28      77     97
185  186    Male   30      99     97
167  168  Female   33      86     95
127  128    Male   40      71     95
7      8  Female   23      18     94
163  164  Female   31      81     93
141  142    Male   32      75     93
173  174    Male   36      87     92

In [55]:
df.nlargest(10, 'Score')

      ID  Gender  Age  Income  Score
11    12  Female   35      19     99
19    20  Female   35      23     98
145  146    Male   28      77     97
185  186    Male   30      99     97
127  128    Male   40      71     95
167  168  Female   33      86     95
7      8  Female   23      18     94
141  142    Male   32      75     93
163  164  Female   31      81     93
33    34    Male   18      33     92

In [56]:
# SELECT * FROM cust order by score desc limit 10 offset 10
df.nlargest(20, 'Score').tail(10)

      ID  Gender  Age  Income  Score
41    42    Male   24      38     92
173  174    Male   36      87     92
123  124    Male   39      69     91
193  194  Female   38     113     91
149  150    Male   34      78     90
179  180    Male   35      93     90
155  156  Female   27      78     89
135  136  Female   29      73     88
151  152    Male   39      78     88
183  184  Female   29      98     88

In [57]:
# SELECT * FROM cust order by score desc limit 10 offset 10
# without nlargest function
df.sort_values('Score', ascending=False).iloc[10:20]

      ID  Gender  Age  Income  Score
41    42    Male   24      38     92
33    34    Male   18      33     92
123  124    Male   39      69     91
193  194  Female   38     113     91
149  150    Male   34      78     90
179  180    Male   35      93     90
155  156  Female   27      78     89
135  136  Female   29      73     88
151  152    Male   39      78     88
183  184  Female   29      98     88