In [4]:
import pandas as pd

In [5]:
cust = pd.read_csv(r'C:\Users\91942\Desktop\11.11\agree\SNOW\pandas\datasets1\datasets1\shoppingmall.csv')
cust.head(10)

   ID  Gender  Age  Income  Score
0   1    Male   19      15     39
1   2    Male   21      15     81
2   3  Female   20      16      6
3   4  Female   23      16     77
4   5  Female   31      17     40
5   6  Female   22      17     76
6   7  Female   35      18      6
7   8  Female   23      18     94
8   9    Male   64      19      3
9  10  Female   30      19     72

In [6]:
shop = pd.read_csv(r'C:\Users\91942\Desktop\11.11\agree\SNOW\pandas\datasets1\datasets1\shopping_customers.csv')
shop.head(10)

    ID  Gender  Age  Income  Score
0  201    Male   61      31     39
1  202    Male   63      31     81
2  203  Female   59      23      6
3  204  Female   37      23     77
4  205  Female   45      19     40
5  206  Female   47      19     76
6  207  Female   55      32      6
7  208  Female   23      24     94
8  209    Male   28      25      3
9  210  Female   29      17     72

In [7]:
#  select * from cust where income > 50 UNION ALL
# select * from shop where income < 45
pd.concat([
    cust[cust['Income'] > 50],
    shop[shop['Income']< 45]
])

     ID  Gender  Age  Income  Score
74   75    Male   59      54     47
75   76    Male   26      54     54
76   77  Female   45      54     53
77   78    Male   40      54     48
78   79  Female   23      54     52
..  ...     ...  ...     ...    ...
15  216    Male   64      26     79
16  217  Female   67      26     35
17  218    Male   67      27     66
18  219    Male   20      28     29
19  220  Female   23      24     98

[146 rows x 5 columns]

In [8]:
pd.concat([
    cust[cust['Income'] > 50],
    shop[shop['Income'] < 45]
]).drop_duplicates()

     ID  Gender  Age  Income  Score
74   75    Male   59      54     47
75   76    Male   26      54     54
76   77  Female   45      54     53
77   78    Male   40      54     48
78   79  Female   23      54     52
..  ...     ...  ...     ...    ...
15  216    Male   64      26     79
16  217  Female   67      26     35
17  218    Male   67      27     66
18  219    Male   20      28     29
19  220  Female   23      24     98

[146 rows x 5 columns]

In [10]:
cust.shape

(200, 5)

In [11]:
cust.head()

   ID  Gender  Age  Income  Score
0   1    Male   19      15     39
1   2    Male   21      15     81
2   3  Female   20      16      6
3   4  Female   23      16     77
4   5  Female   31      17     40

In [ ]:
# added a data at the bottom
cust.loc[len(cust)] = [500, 'male', 20, 30, 40]

In [ ]:
# checkd a data added or not
len(cust)

201

In [18]:
cust.loc[len(cust)] = [600,'female', 100,200,300]

In [36]:
cust.loc[203] = [700, 'male', 101,201,301]
cust

      ID  Gender  Age  Income  Score
0      1    Male   19      15     39
1      2    Male   21      15     81
2      3  Female   20      16      6
3      4  Female   23      16     77
4      5  Female   31      17     40
..   ...     ...  ...     ...    ...
198  199    Male   32     137     18
199  200    Male   30     137     83
200  500    male   20      30     40
201  600  female  100     200    300
203  700    male  101     201    301

[203 rows x 5 columns]

In [37]:
# adde on top of cust
new_row = pd.DataFrame([[5,'male', 2,3,4]], columns=cust.columns)

In [ ]:
# for the top 
pd.concat([new_row, cust])

      ID  Gender  Age  Income  Score
0      5    male    2       3      4
0      1    Male   19      15     39
1      2    Male   21      15     81
2      3  Female   20      16      6
3      4  Female   23      16     77
..   ...     ...  ...     ...    ...
198  199    Male   32     137     18
199  200    Male   30     137     83
200  500    male   20      30     40
201  600  female  100     200    300
203  700    male  101     201    301

[204 rows x 5 columns]

In [43]:
# update cust set score = 11 where score = 10
cust.loc[cust['Score'] == 11, 'Score'] == 10

128    False
Name: Score, dtype: bool

In [44]:
cust[cust.Score==11]

      ID Gender  Age  Income  Score
128  129   Male   59      71     11

In [47]:
# delete from cust where score = 11
cust = cust.drop(cust[cust['Score'] == 11].index)

In [49]:
cust[cust.Score == 11]

Empty DataFrame
Columns: [ID, Gender, Age, Income, Score]
Index: []