In [1]:
# groupby() method -> to split the data into groups and then apply any operation on groups

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\91942\Downloads\datasets1\datasets1\cities_weather.csv')
df

           day      city  temperature  windspeed   event
0   01-01-2017  new york           32          6    Rain
1   01-02-2017  new york           36          7   Sunny
2   01-03-2017  new york           28         12    Snow
3   01-04-2017  new york           33          7   Sunny
4   01-01-2017    mumbai           90          5   Sunny
5   01-02-2017    mumbai           85         12     Fog
6   01-03-2017    mumbai           87         15     Fog
7   01-04-2017    mumbai           92          5    Rain
8   01-01-2017     paris           45         20   Sunny
9   01-02-2017     paris           50         13  Cloudy
10  01-03-2017     paris           54          8  Cloudy
11  01-04-2017     paris           42         10  Cloudy

In [4]:
df1 = df.groupby('city')
df1

In [5]:
for city, data in df1:
    print(data)

          day    city  temperature  windspeed  event
4  01-01-2017  mumbai           90          5  Sunny
5  01-02-2017  mumbai           85         12    Fog
6  01-03-2017  mumbai           87         15    Fog
7  01-04-2017  mumbai           92          5   Rain
          day      city  temperature  windspeed  event
0  01-01-2017  new york           32          6   Rain
1  01-02-2017  new york           36          7  Sunny
2  01-03-2017  new york           28         12   Snow
3  01-04-2017  new york           33          7  Sunny
           day   city  temperature  windspeed   event
8   01-01-2017  paris           45         20   Sunny
9   01-02-2017  paris           50         13  Cloudy
10  01-03-2017  paris           54          8  Cloudy
11  01-04-2017  paris           42         10  Cloudy

In [6]:
# Aggregate function : are the function that act on 
# group of element max(), min(), mean(),
# sum(), median(), std(), prod(), count()

In [7]:
df1.get_group('mumbai')

          day    city  temperature  windspeed  event
4  01-01-2017  mumbai           90          5  Sunny
5  01-02-2017  mumbai           85         12    Fog
6  01-03-2017  mumbai           87         15    Fog
7  01-04-2017  mumbai           92          5   Rain

In [8]:
df1.get_group('paris')

           day   city  temperature  windspeed   event
8   01-01-2017  paris           45         20   Sunny
9   01-02-2017  paris           50         13  Cloudy
10  01-03-2017  paris           54          8  Cloudy
11  01-04-2017  paris           42         10  Cloudy

In [9]:
df1.get_group('mumbai').max()

day            01-04-2017
city               mumbai
temperature            92
windspeed              15
event               Sunny
dtype: object

In [10]:
df1.agg('max')

                 day  temperature  windspeed  event
city
mumbai    01-04-2017           92         15  Sunny
new york  01-04-2017           36         12  Sunny
paris     01-04-2017           54         20  Sunny

In [11]:
df1.agg('min')

                 day  temperature  windspeed   event
city
mumbai    01-01-2017           85          5     Fog
new york  01-01-2017           28          6    Rain
paris     01-01-2017           42          8  Cloudy

In [15]:
df1['temperature'].agg(['max', 'min'])

          max  min
city
mumbai     92   85
new york   36   28
paris      54   42

In [22]:
# find avg speed in New york
df1 = df.groupby('city')['windspeed'].mean()
df1['new york']
print("the avg windspeed new york is = ", df1['new york'])

the avg windspeed new york is =  8.0

In [36]:
# min temp and max windspeed in new york
temp = df.groupby('city')['temperature'].min()
wind = df.groupby('city')['windspeed'].max()
print("the minimum tem is = ", temp['new york'])
print("the max windspeed is =", wind['new york'])

the minimum tem is =  28
the max windspeed is = 12

In [ ]:
# 2nd way
df1.agg({'temperature': 'min', 'windspeed': 'max'})

temperature    12
windspeed      20
Name: windspeed, dtype: int64

In [56]:
#  find min, max on temperature - sum and avg on windspeed ?
df = df.groupby('city')
df1 = df.get_group('new york')
df1.agg({
    'temperature': ['min', 'max'],
    'windspeed': ['sum', 'mean']
})

      temperature  windspeed
min          28.0        NaN
max          36.0        NaN
sum           NaN       32.0
mean          NaN        8.0

In [57]:
# total dataset
df.agg({'temperature' : ['min', 'max'], 'windspeed' : ['sum', 'mean']})

         temperature     windspeed
                 min max       sum   mean
city
mumbai            85  92        37   9.25
new york          28  36        32   8.00
paris             42  54        51  12.75