In [3]:
import pandas as pd

In [4]:
df1 = {'player name': ['rahul dravid', 'virat kohli', 'rohit sahrma','ricky ponting'],
       'age': [10,20, 40, 30]}
df1

{'player name': ['rahul dravid',
  'virat kohli',
  'rohit sahrma',
  'ricky ponting'],
 'age': [10, 20, 40, 30]}

In [5]:
df1 = pd.DataFrame({'player name': ['rahul dravid', 'virat kohli', 'rohit sahrma','ricky ponting'],
       'age': [10,20, 40, 30]})
df1

     player name  age
0   rahul dravid   10
1    virat kohli   20
2   rohit sahrma   40
3  ricky ponting   30

In [6]:
df2 = pd.DataFrame({
    'player name' : ['rahul dravid', 'sachin tendulkar', 'virat kohli', 'Hardik Pandya', 'M.S. Dhoni'],
    'salary' : [1000000, 500000, 2000000, 1500000, 2500000]
})

df2

        player name   salary
0      rahul dravid  1000000
1  sachin tendulkar   500000
2       virat kohli  2000000
3     Hardik Pandya  1500000
4        M.S. Dhoni  2500000

In [7]:
# inner join
pd.merge (df1, df2, on = 'player name', how = 'inner')

    player name  age   salary
0  rahul dravid   10  1000000
1   virat kohli   20  2000000

In [8]:
# left join
pd.merge (df1, df2, on = 'player name', how = 'left')

     player name  age     salary
0   rahul dravid   10  1000000.0
1    virat kohli   20  2000000.0
2   rohit sahrma   40        NaN
3  ricky ponting   30        NaN

In [9]:
# right join
pd.merge (df1, df2, on = 'player name', how = 'right')

        player name   age   salary
0      rahul dravid  10.0  1000000
1  sachin tendulkar   NaN   500000
2       virat kohli  20.0  2000000
3     Hardik Pandya   NaN  1500000
4        M.S. Dhoni   NaN  2500000

In [10]:
# outer join : means union of left and right join
pd.merge (df1, df2, on = 'player name', how = 'outer')

        player name   age     salary
0     Hardik Pandya   NaN  1500000.0
1        M.S. Dhoni   NaN  2500000.0
2      rahul dravid  10.0  1000000.0
3     ricky ponting  30.0        NaN
4      rohit sahrma  40.0        NaN
5  sachin tendulkar   NaN   500000.0
6       virat kohli  20.0  2000000.0

In [11]:
df3 = pd.DataFrame({
    'Player Name' : ['Rahul Dravid', 'Sachin Tendulkar', 'Virat Kohli', 'Ricky Ponting', 'M.S. Dhoni'],
    'Age' : [48, 50, 34, 42, 40],
})
df3

        Player Name  Age
0      Rahul Dravid   48
1  Sachin Tendulkar   50
2       Virat Kohli   34
3     Ricky Ponting   42
4        M.S. Dhoni   40

In [12]:
df4 = pd.DataFrame({
    'Sports Person' : ['Rahul Dravid', 'Sachin Tendulkar', 'Virat Kohli', 'Hardik Pandya', 'M.S. Dhoni'],
    'salary' : [1000000, 500000, 2000000, 1500000, 2500000]
})

df4

      Sports Person   salary
0      Rahul Dravid  1000000
1  Sachin Tendulkar   500000
2       Virat Kohli  2000000
3     Hardik Pandya  1500000
4        M.S. Dhoni  2500000

In [13]:
# Join Dataframes even when two DF have diffrant col name
#👉 Joins DataFrames based on matching column values.
# It checks:
# Player Name == Sports Person
pd.merge (df3, df4, left_on = 'Player Name', right_on = 'Sports Person', how = 'inner')

        Player Name  Age     Sports Person   salary
0      Rahul Dravid   48      Rahul Dravid  1000000
1  Sachin Tendulkar   50  Sachin Tendulkar   500000
2       Virat Kohli   34       Virat Kohli  2000000
3        M.S. Dhoni   40        M.S. Dhoni  2500000

In [14]:
pd.concat ([df3, df4], ignore_index=True)

        Player Name   Age     Sports Person     salary
0      Rahul Dravid  48.0               NaN        NaN
1  Sachin Tendulkar  50.0               NaN        NaN
2       Virat Kohli  34.0               NaN        NaN
3     Ricky Ponting  42.0               NaN        NaN
4        M.S. Dhoni  40.0               NaN        NaN
5               NaN   NaN      Rahul Dravid  1000000.0
6               NaN   NaN  Sachin Tendulkar   500000.0
7               NaN   NaN       Virat Kohli  2000000.0
8               NaN   NaN     Hardik Pandya  1500000.0
9               NaN   NaN        M.S. Dhoni  2500000.0

In [ ]:
# its not check eny same values in a column direcly joins
# axis = 0 also gives a nan values but axis = 1 are gives not
pd.concat([df3, df4], axis=0)

        Player Name   Age     Sports Person     salary
0      Rahul Dravid  48.0               NaN        NaN
1  Sachin Tendulkar  50.0               NaN        NaN
2       Virat Kohli  34.0               NaN        NaN
3     Ricky Ponting  42.0               NaN        NaN
4        M.S. Dhoni  40.0               NaN        NaN
0               NaN   NaN      Rahul Dravid  1000000.0
1               NaN   NaN  Sachin Tendulkar   500000.0
2               NaN   NaN       Virat Kohli  2000000.0
3               NaN   NaN     Hardik Pandya  1500000.0
4               NaN   NaN        M.S. Dhoni  2500000.0

In [18]:
pd.concat([df3, df4], axis=1)

        Player Name  Age     Sports Person   salary
0      Rahul Dravid   48      Rahul Dravid  1000000
1  Sachin Tendulkar   50  Sachin Tendulkar   500000
2       Virat Kohli   34       Virat Kohli  2000000
3     Ricky Ponting   42     Hardik Pandya  1500000
4        M.S. Dhoni   40        M.S. Dhoni  2500000