In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\91942\Downloads\datasets1\datasets1\titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.iloc[4,3]  # row position 4 column position 3

'Allen, Mr. William Henry'

In [ ]:
df.iloc[1,6]  # row position 1 column position 6

np.int64(1)

In [ ]:
# iloc[row_selection]
# here we prints only a row but by default its prints all the column
df.iloc[5:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [9]:
# iloc[row_selection, column_selection]
# but here we print row + specific columns
df.iloc[5:10, 0:4]

,PassengerId,Survived,Pclass,Name
5,6,0,3,"Moran, Mr. James"
6,7,0,1,"McCarthy, Mr. Timothy J"
7,8,0,3,"Palsson, Master. Gosta Leonard"
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)"
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)"

In [ ]:
# : → all rows
# 4 → column at position 4
df.iloc[:,4]
df.shape  # for length

(891, 12)

In [22]:
# i want to display whos age is greater than 30 and sex is male
df[(df['Age'] > 30) & (df['Sex'] == 'male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...,...,...
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [29]:
# now i wann only prints names and sexd
df[(df['Age'] > 30) & (df['Sex'] == 'male')] [['Name','Parch']]

                                     Name  Parch
4                Allen, Mr. William Henry      0
6                 McCarthy, Mr. Timothy J      0
13            Andersson, Mr. Anders Johan      5
20                   Fynney, Mr. Joseph J      0
21                  Beesley, Mr. Lawrence      0
..                                    ...    ...
867  Roebling, Mr. Washington Augustus II      0
872              Carlsson, Mr. Frans Olof      0
873           Vander Cruyssen, Mr. Victor      0
881                    Markun, Mr. Johann      0
890                   Dooley, Mr. Patrick      0

[202 rows x 2 columns]

In [32]:
# only display female name
df[(df['Sex'] == 'female')] [['Name','Parch']]

                                                  Name  Parch
1    Cumings, Mrs. John Bradley (Florence Briggs Th...      0
2                               Heikkinen, Miss. Laina      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)      0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)      2
9                  Nasser, Mrs. Nicholas (Adele Achem)      0
..                                                 ...    ...
880       Shelley, Mrs. William (Imanita Parrish Hall)      1
882                       Dahlberg, Miss. Gerda Ulrika      0
885               Rice, Mrs. William (Margaret Norton)      5
887                       Graham, Miss. Margaret Edith      0
888           Johnston, Miss. Catherine Helen "Carrie"      2

[314 rows x 2 columns]

In [ ]:
# where condition

In [33]:
import numpy as np

In [36]:
df = pd.DataFrame(data = np.random.randint(0, 100, (4,3)),
columns=('test1', 'test2', 'test3'),
index=['vinay', 'tushar', 'vrushabh', 'kartik'])
print(df)

          test1  test2  test3
vinay        88     82     22
tushar       13     34     63
vrushabh     94     71     97
kartik       96     87     55

In [37]:
# if marks are greater than 70 or 80 replace those marks with A+ grade
df.where(df<=70, 'A+')

         test1 test2 test3
vinay       A+    A+    22
tushar      13    34    63
vrushabh    A+    A+    A+
kartik      A+    A+    55

In [39]:
# for > 30 bad marks
df.where(df['test3'] > 30, 'bad')

         test1 test2 test3
vinay      bad   bad   bad
tushar      13    34    63
vrushabh    94    71    97
kartik      96    87    55

In [ ]:
# df['test3'] = df['test3'].where(df['test3'] > 30, 'bad')  
# not give a output insted of number 
# we already wrote a string 'bad' in a above program

In [ ]:
df.where(df != 87, 'medium')

          test1   test2 test3
vinay        88      82   bad
tushar       13      34    63
vrushabh     94      71    97
kartik       96  medium    55

In [48]:
# using lambda
df.where(lambda x: df != 13 ,'medium')

           test1  test2 test3
vinay         88     82   bad
tushar    medium     34    63
vrushabh      94     71    97
kartik        96     87    55

In [50]:
df1 = pd.DataFrame(data = np.random.randint(1,100, (4,3)),
columns=('test1', 'test2', 'test3'),
index=['vinay', 'tushar', 'vrushabh', 'kartik'])
df1

          test1  test2  test3
vinay        37     83     25
tushar       80     95     77
vrushabh     36     55     87
kartik       30     90     27

In [56]:
# replace the value based on condition df to df1
# df1.where(df <= 95, df1)

In [58]:
# df1.where(df <= 80, df + df1)
# both give a error because we write some string df1 dataset 'medium, 'bad' etc