In [ ]:
# Window function = calculation on a moving group of rows (not whole column)

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# “Does each row depend on previous rows or a subset of rows?”
# yes means here used a compulsory window function

In [2]:
df = pd.DataFrame({
    'a': [1,2,3,4,5,6],
    'b':[10, np.nan, np.nan, np.nan, np.nan, 30]
})
df

   a     b
0  1  10.0
1  2   NaN
2  3   NaN
3  4   NaN
4  5   NaN
5  6  30.0

In [3]:
# cumulative sum
df['a_cumsum'] = df['a'].cumsum()
df

   a     b  a_cumsum
0  1  10.0         1
1  2   NaN         3
2  3   NaN         6
3  4   NaN        10
4  5   NaN        15
5  6  30.0        21

In [4]:
# cummu prod of 'a'
df['cumprod_a'] = df['a'].cumprod()
print("the prod is = ", df)

the prod is =     a     b  a_cumsum  cumprod_a
0  1  10.0         1          1
1  2   NaN         3          2
2  3   NaN         6          6
3  4   NaN        10         24
4  5   NaN        15        120
5  6  30.0        21        720

In [ ]:
# Rolling window: means moving window
# 1. What is rolling(window=2)?
#👉 It creates a moving window of size 2 rows
#“At each row, look at current row + previous 1 row”

In [ ]:
# rolling window to find rolling sum of 'a'